DROP TABLE IF EXISTS GameConverted;

DROP SEQUENCE IF EXISTS GameConverted_seq;

CREATE SEQUENCE GameConverted_seq;

CREATE TABLE GameConverted  (
    gameid BIGINT DEFAULT NEXTVAL ('GameConverted_seq') NOT NULL PRIMARY KEY,
    player_name VARCHAR(100),
    time_played BIGINT NOT NULL,
    score BIGINT NOT NULL,
    shots2 BIGINT NOT NULL,
    scored2 BIGINT NOT NULL,
    shots3 BIGINT NOT NULL,
    scored3 BIGINT NOT NULL,
    shots1 BIGINT NOT NULL,
    scored1 BIGINT NOT NULL,
    rebounds_offensive BIGINT NOT NULL,
    rebounds_defensive BIGINT NOT NULL,
    rebounds BIGINT NOT NULL,
    passes BIGINT NOT NULL,
    interceptions BIGINT NOT NULL,
    turnovers BIGINT NOT NULL,
    blocks BIGINT NOT NULL,
    blocked BIGINT NOT NULL,
    fouls BIGINT NOT NULL,
    fouled BIGINT NOT NULL,
    index BIGINT NOT NULL,
    game_date TIMESTAMP(0),
    team VARCHAR(255),
    rival VARCHAR(255),
    home VARCHAR(255)
);

CREATE SEQUENCE IF NOT EXISTS user_accounts_seq;

CREATE TABLE IF NOT EXISTS user_accounts (
    user_id BIGINT NOT NULL DEFAULT nextval('user_accounts_seq') PRIMARY KEY,
    username varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    role varchar(255),
    enabled boolean NOT NULL
);

DROP TABLE IF EXISTS BATCH_JOB_INSTANCE CASCADE;

CREATE TABLE BATCH_JOB_INSTANCE  (
    JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
    VERSION BIGINT ,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION CASCADE;

CREATE TABLE BATCH_JOB_EXECUTION  (
    JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
    VERSION BIGINT  ,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP(0) NOT NULL,
    START_TIME TIMESTAMP(0) DEFAULT NULL ,
    END_TIME TIMESTAMP(0) DEFAULT NULL ,
    STATUS VARCHAR(10) ,
    EXIT_CODE VARCHAR(2500) ,
    EXIT_MESSAGE VARCHAR(2500) ,
    LAST_UPDATED TIMESTAMP(0),
    JOB_CONFIGURATION_LOCATION VARCHAR(2500) NULL,
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
    references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS CASCADE;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
    JOB_EXECUTION_ID BIGINT NOT NULL ,
    TYPE_CD VARCHAR(6) NOT NULL ,
    KEY_NAME VARCHAR(100) NOT NULL ,
    STRING_VAL VARCHAR(250) ,
    DATE_VAL TIMESTAMP(0) DEFAULT NULL ,
    LONG_VAL BIGINT ,
    DOUBLE_VAL DOUBLE PRECISION ,
    IDENTIFYING CHAR(1) NOT NULL ,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION CASCADE;

CREATE TABLE BATCH_STEP_EXECUTION  (
    STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    START_TIME TIMESTAMP(0) NOT NULL ,
    END_TIME TIMESTAMP(0) DEFAULT NULL ,
    STATUS VARCHAR(10) ,
    COMMIT_COUNT BIGINT ,
    READ_COUNT BIGINT ,
    FILTER_COUNT BIGINT ,
    WRITE_COUNT BIGINT ,
    READ_SKIP_COUNT BIGINT ,
    WRITE_SKIP_COUNT BIGINT ,
    PROCESS_SKIP_COUNT BIGINT ,
    ROLLBACK_COUNT BIGINT ,
    EXIT_CODE VARCHAR(2500) ,
    EXIT_MESSAGE VARCHAR(2500) ,
    LAST_UPDATED TIMESTAMP(0),
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT ,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
    references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT ,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

DROP SEQUENCE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP SEQUENCE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP SEQUENCE IF EXISTS BATCH_JOB_SEQ;


CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;


CREATE SEQUENCE IF NOT EXISTS authorities_seq;

CREATE TABLE IF NOT EXISTS authorities (
    auth_id BIGINT NOT NULL DEFAULT nextval('authorities_seq') PRIMARY KEY,
    username varchar(255) NOT NULL,
    authority varchar(255) NOT NULL
);


DROP SEQUENCE IF EXISTS userstatsets_seq;

CREATE SEQUENCE IF NOT EXISTS userstatsets_seq;

DROP TABLE IF EXISTS userstatsets;

CREATE TABLE IF NOT EXISTS userstatsets (
    userstatset_id BIGINT NOT NULL DEFAULT nextval('userstatsets_seq') PRIMARY KEY,
    userstatset_name varchar(255) NOT NULL,
    players varchar(255) NOT NULL,
    column_name varchar(255) NOT NULL,
    from_date BIGINT NOT NULL,
    to_date BIGINT NOT NULL,
    show_average boolean NOT NULL,
    user_name varchar(255) NOT NULL
);
